# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_question_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
