# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 00:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_question_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='active',
        ),
        migrations.AddField(
            model_name='question',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 21, 0, 36, 26, 933638, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 22, 0, 36, 26, 933596, tzinfo=utc), verbose_name='date published'),
        ),
    ]
